import { type NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/Header";
import Topics from "~/components/Topics";
import Notes from "~/components/Notes";

const Home: NextPage = ({}) => {
  return (
    <>
      <Head>
        <title>Notetaker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="mx-5 mt-5 grid grid-cols-4 gap-2 ">
          <Topics />
          <Notes />
        </div>
      </main>
    </>
  );
};

export default Home;
